---
- hosts: pis
  tasks:
    - name: Update repositories cache
      shell: apt-get update
      args:
        warn: False
    - name: Upgrade system
      shell: apt-get upgrade -y
      args:
        warn: False
