---
- hosts: pis
  tasks:
    - name: Update repositories cache
      shell: apt-get update
      args:
        warn: False
    - name: Upgrade system
      shell: apt-get upgrade -y
      args:
        warn: False
    - name: Install hping3
      apt:
        name: hping3
        state: present
    - name: Install python3 interpreter
      apt:
        name: python3
        state: present
    - name: Install git
      apt:
        name: git
        state: present
    - name: Install make
      apt:
        name: make
        state: present
    - name: Install gcc   
      apt:
        name: gcc
        state: present
    - name: Install libnet  
      apt:
        name: libnet1-dev
        state: present
    - name: Clone Git-Respository
      git:
        repo: 'git://git.kali.org/packages/inviteflood.git'
        dest: /root/inviteflood
        update: no
    - name: Compile hack_library
      shell: chdir=/root/inviteflood/hack_library/ make
    - name: Compile inviteflood
      shell: chdir=/root/inviteflood/inviteflood/ make
